### ISSUE TITLE
extjs-socketioprovider installation description

### ISSUE THREAD

**Issue by MrTim** [alexandrubau/extjs-socketioprovider#1]
Hi,

I have ExtJs 6 application and remote NodeJs backend server. And I'd like to try this provider, but the usage description is not very clear. Couple questions:
1. Where exactly the "/socket.io/socket.io.js" should be included?
2. In installation section: where the "npm install" should be fired and what I need to add at app.json?

I think all these questions could be included at the installation section.

Thanks in advance.

**Comment by alexandrubau** [comment]
Hi @MrTim,

1.
If you used Sencha Cmd to generate your application, you should have an `app.json` file. In that file you should have a section, which will inform the Sencha Cmd builder, what other JavaScript files to include in the build process. That's where you specify `/socket.io/socket.io.js`.

If you haven't used Sencha Cmd to build your application, you should include the `/socket/socket.io.js` normally with a script tag, normally as is specified in the socket.io [http://socket.io/docs/].

2.
The command `npm install` needs to be run in the root directory of your project. 

I don't think that this instructions need to be included in the installation section because this represent the basics of using ExtJs, Sencha Cmd, and NPM, it has nothing to do with the Socket Provider that I have implemented.

**Comment by MrTim** [comment]
I already solved my issues but thank for your reply!

**Comment by alexandrubau** [comment]
@MrTim You're welcome. Ant thanks for the star.
